import { useState, useEffect } from 'react';

// Common Unsplash images to represent diverse thumbnails
export const THUMBNAILS: any[] = [
  {
    id: 1,
    title: 'New Documentary',
    category: 'Documentary',
    views: '1.2M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=18-D_6vKI3QrKdXns4kBqhy-4ris6ovKQ&sz=w1200',
    featured: true,
  },
  {
    id: 2,
    title: 'CR7 - The True Cost of Greatness',
    category: 'Documentary',
    views: '8.4M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1d2HBuWskVa-G2faqpsEwgXxUjoNJKGbk&sz=w1200',
    featured: true,
  },
  {
    id: 3,
    title: 'The Real Squad Game',
    category: 'Documentary',
    views: '5.2M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1ZWtTiAMepR9w06tNT4aI9Mdrkzy-Vhi7&sz=w1200',
    featured: true,
  },
  {
    id: 4,
    title: 'The Toxic Truth of the Medical Industry',
    category: 'Documentary',
    views: '3.1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=15I9fXypcSZz6Pf5wu27qi8-jWu43OoyI&sz=w1200',
    featured: true,
  },
  {
    id: 5,
    title: 'The True Story Behind The Boarding School',
    category: 'Documentary',
    views: '1.9M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1yiVVlE8rQjHP-qSCwdGC29u0kG-7_-ZD&sz=w1200',
    featured: true,
  },
  {
    id: 6,
    title: 'AI Stack On Budget',
    category: 'Finance',
    views: '2.5M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1aEP1aGqeY7JzvBAaKROr7fF74KJ_ZnDQ&sz=w1200',
    featured: true,
  },
  {
    id: 7,
    title: "This Isn't Gambling?",
    category: 'Finance',
    views: '1.8M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1xMzJiu_R_C4lV9afd-ORy0egcRImWL4G&sz=w1200',
    featured: true,
  },
  {
    id: 8,
    title: 'Revenue $65,000',
    category: 'Finance',
    views: '3.2M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=13xQv11n3RYBzUzZerwRtW3EhUc_QAumo&sz=w1200',
    featured: true,
  },
  {
    id: 9,
    title: 'Rank #1 Everywhere',
    category: 'Finance',
    views: '4.1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1b-doEt1c4F-T7nktNh0HBEfBHuzOgmb3&sz=w1200',
    featured: true,
  },
  {
    id: 10,
    title: 'The Rise Of Allocation Economy.',
    category: 'Finance',
    views: '2.9M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1D9UG72ClFSzF_kIEYjhLzEmiloI5ldzr&sz=w1200',
    featured: true,
  },
  {
    id: 11,
    title: '$1 Webinar System',
    category: 'Finance',
    views: '1.1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1i0B560jg3l_74Xy_jlVEs53NTDyk3JME&sz=w1200',
    featured: true,
  },
  {
    id: 12,
    title: 'Scaling Your Online Business',
    category: 'Finance',
    views: '3.5M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1SIxXfaT4PGGa7snkoLJLjiQZxLJbEJOh&sz=w1200',
    featured: true,
  },
  {
    id: 13,
    title: 'Movie 1',
    category: 'Movies',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1PM6ShZ3EW0dzHQcUWSELR6sPlWXa-mq6&sz=w1200',
    featured: true,
  },
  {
    id: 14,
    title: 'Movie 2',
    category: 'Movies',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1vJtxBryk1RjLbX3Pv6nixO5nHcWb0l1K&sz=w1200',
    featured: true,
  },
  {
    id: 15,
    title: 'Movie 3',
    category: 'Movies',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1Tlcq-9jxPpMziok26R8m_Lnkw4Ao2GBY&sz=w1200',
    featured: true,
  },
  {
    id: 16,
    title: 'Movie 4',
    category: 'Movies',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1IT06bJJJva22aQ-oQTLhZSLwcK--V3wf&sz=w1200',
    featured: true,
  },
  {
    id: 17,
    title: 'History 1',
    category: 'History',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1tSTbqfzkNNMv3BCNFQfn70QtYisMqkzi&sz=w1200',
    featured: true,
  },
  {
    id: 18,
    title: 'History 2',
    category: 'History',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1O1YJFqeZnRwltC-lMmD2Ml2xkcB_tMt3&sz=w1200',
    featured: true,
  },
  {
    id: 19,
    title: 'History 3',
    category: 'History',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1KTuYkOqVUjbQVYrXuCo6KPffjyY1LpoO&sz=w1200',
    featured: true,
  },
  {
    id: 20,
    title: 'Finance Insights',
    category: 'Finance',
    views: '1.5M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1vDr0-VqbVzfcFPIpJ2IhzTrkDVj2aGYf&sz=w1200',
    featured: true,
  },
  {
    id: 21,
    title: 'Other 1',
    category: 'Others',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=193b39BB8F_SVtFstflzu8Ik7ozV33iwl&sz=w1200',
    featured: true,
  },
  {
    id: 22,
    title: 'Other 2',
    category: 'Others',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1SprV56c7dIsd8XuB4oSPO2AHF7NlUDVP&sz=w1200',
    featured: true,
  },
  {
    id: 23,
    title: 'Other 3',
    category: 'Others',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1Rd1yxBgWBpeGxRHNpAWLW_QmrThKBjwz&sz=w1200',
    featured: true,
  },
  {
    id: 24,
    title: 'Other 4',
    category: 'Others',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1xa77nJ1Y2GB27it7_Dl9wINg2kLA3Dk1&sz=w1200',
    featured: true,
  },
  {
    id: 25,
    title: 'Other 5',
    category: 'Others',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1ypAo1w6vpK7oBbEp0_WDbJVxejj0xy0b&sz=w1200',
    featured: true,
  },
  {
    id: 26,
    title: 'Other 6',
    category: 'Others',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1bhEKsYkFp4gKmlaAzGAWKgAFcY3LJZ62&sz=w1200',
    featured: true,
  },
  {
    id: 27,
    title: 'Other 7',
    category: 'Others',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=15dNPe0i4AnIbCpeii-r6IW7LcDIwUIzx&sz=w1200',
    featured: true,
  },
  {
    id: 28,
    title: 'Other 8',
    category: 'Others',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1omVwQec6KjV71JknFg_yT-zjcEpXKQOA&sz=w1200',
    featured: true,
  },
  {
    id: 29,
    title: 'Other 9',
    category: 'Others',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1N5Q64WXZ-JUhC-90_raWbSwGU1TXanPv&sz=w1200',
    featured: true,
  },
  {
    id: 30,
    title: 'Podcast 1',
    category: 'Podcast',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1NcASuO1kUdUII_5vw0Xw7XTCWO1nIEgS&sz=w1200',
    featured: true,
  },
  {
    id: 31,
    title: 'Podcast 2',
    category: 'Podcast',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1EBL8-HaMyfz3BnfT-VCjbYoIEXRBMChj&sz=w1200',
    featured: true,
  },
  {
    id: 32,
    title: 'Documentary 6',
    category: 'Documentary',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1VKHL4mdVk6s9yhcW6buTiI6u9SwTWJcs&sz=w1200',
    featured: true,
  },
  {
    id: 33,
    title: 'Royal Family 1',
    category: 'Royal family',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1I2yN7f77Hs9wkrJzdtbA7ZEO6cGz2cEX&sz=w1200',
    featured: true,
  },
  {
    id: 34,
    title: 'Royal Family 2',
    category: 'Royal family',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=15ARMDpZ0P8DiotrEo_XRS_C3t-8mcHLm&sz=w1200',
    featured: true,
  },
  {
    id: 35,
    title: 'Royal Family 3',
    category: 'Royal family',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1dAMTVsL5XTTjqllT4hQwyKxsTZnWQhlr&sz=w1200',
    featured: true,
  },
  {
    id: 36,
    title: 'Royal Family 4',
    category: 'Royal family',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1iy1x4RvZUVoCj2G17usRWdIeQ1ZHTsaE&sz=w1200',
    featured: true,
  },
  {
    id: 37,
    title: 'Royal Family 5',
    category: 'Royal family',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1dqX1q9-y0SQDB5RYhD9llI-AjrnYL1wd&sz=w1200',
    featured: true,
  },
  {
    id: 38,
    title: 'Royal Family 6',
    category: 'Royal family',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1sgrTC21-ibi5YEnIdz8HR85fqm7w8U3C&sz=w1200',
    featured: true,
  },
  {
    id: 39,
    title: 'Royal Family 7',
    category: 'Royal family',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1Rcyt3ZTSQkzGwZoaaH7kr6gfsKQMErkP&sz=w1200',
    featured: true,
  },
  {
    id: 40,
    title: 'Other 10',
    category: 'Others',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1YZdJLXG4Vr27tQ65MaJWJzCZtt0MflgA&sz=w1200',
    featured: true,
  },
  {
    id: 41,
    title: 'Podcast 10',
    category: 'Podcast',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1ApYL0ztDSasz2dwI1lEGlqNQzoskLflL&sz=w1200',
    featured: true,
  },
  {
    id: 42,
    title: 'Other 11',
    category: 'Others',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1B80JOMqgCrZP1gjJJTNJHt3_OMCqmP8f&sz=w1200',
    featured: true,
  },
  {
    id: 43,
    title: 'Movie 5',
    category: 'Movies',
    views: '1M+',
    imageUrl: 'https://drive.google.com/thumbnail?id=1MuU1rIYLANCJ-7ChXVQxu_NsFZTzp_ZX&sz=w1200',
    featured: true,
  }
];

export const CATEGORIES = ['All', 'Documentary', 'Podcast', 'Finance', 'History', 'Movies', 'Royal family', 'Others'];




